[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.91.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --minify"

[context.split1.environment]
HUGO_VERSION = "0.91.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.1"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.91.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"


[[redirects]]
  from = "/wa1/"
  to = "https://wa.link/0fncje"
  status = 301
  force = true

[[redirects]]
  from = "/wa2/"
  to = "https://wa.link/ed7wp9"
  status = 301
  force = true