---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/sadap
  label: Sadap
  create: all
  match: "**/*"
  templates:
  - content
- type: directory
  path: content/ulasan
  label: Ulasan
  create: all
  match: "**/*"
  templates:
  - content
- type: document
  path: content/ulasan/**/*
  label: ulasan
  read_only: true
upload_dir: static
public_path: ''
front_matter_path: 'uploads/:year:/:month:/:day:/:filename:'
use_front_matter_path: false
file_template: 'uploads/:year:/:month:/:day:/:filename:'
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
